### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by gewooneendeveloper** [picturae/OaiPmh#12]
Hi, currently @kennisnet this lib is used in a legacy project.
For a new project I copied the code and made it PHP7.4 compatible and added support for different record formats. In our case json-ld

If this project is still active i could provide a full update for PHP7.4 and support for multiple formats, but it will be a big PR. 

Best regards,
Andreas

**Comment by Pin0** [comment]
Hai @andreaswarnaar,

As you mentioned this project is not actively maintained. However if you could create a pull request we could merge it and create a 1.0.0 tag for this. This way it won't affect any other installations.

Thanks!

**Comment by saidatom** [comment]
Hello all,

Can anyone check #14 ?

Best regards,
Alex

**Comment by Pin0** [comment]
This project will no longer be maintained.
