### ISSUE TITLE
One of the unit tests fails because of problems wile validating against xsd

### ISSUE THREAD

**Issue by alexandar-mitsev** [picturae/OaiPmh#2]
One of the unit tests fails because of problems wile validating against http://www.openarchives.org/OAI/2.0/oai_dc/

**Comment by alexandar-mitsev** [comment]
Seems the problem comes from the validating itself, which validates only against one of the schemes.
The test is temporary disabled. Can be enabled again when fixed in ProviderTest between line 340 and 343.

**Comment by Pin0** [comment]
closed due to inactivity
